music/urls.py
from django.conf.urls import url

from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^vocabularys/(?P<filter_by>[a-zA_Z]+)/$', views.vocabularys, name='vocabularys'),
    url(r'^(?P<topic_id>[0-9]+)/e2vn/(?P<type_compare>[0-9]+)$', views.compare_vocabualry, name='compare_word'),
    url(r'^create_topic/$', views.create_topic, name='create_topic'),
    url(r'^(?P<topic_id>[0-9]+)/create_vocabulary/$', views.create_vocabulary, name='create_vocabulary'),
    url(r'^(?P<topic_id>[0-9]+)/delete_vocabulary/(?P<vocabulary_id>[0-9]+)/(?P<local_delete>[0-9]+)$',
        views.delete_vocabulary,
        name='delete_vocabulary'),
    url(r'^(?P<topic_id>[0-9]+)/delete_topic/$', views.delete_topic, name='delete_topic'),
    url(r'^(?P<topic_id>[0-9]+)/$', views.detail, name='detail'),

]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
import random

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from django.utils import timezone


class Topic(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=True)
    topic_title = models.CharField(max_length=500)
    topic_logo = models.FileField()

    def __str__(self):
        return self.topic_title


class Vocabulary(models.Model):
    vocabulary_title = models.CharField(max_length=45)
    type = models.IntegerField(blank=True, null=True)
    story = models.CharField(max_length=100, blank=True, null=True)
    note = models.CharField(max_length=100, blank=True, null=True)
    pronounce = models.CharField(max_length=20, blank=True, null=True)
    mean = models.CharField(max_length=20, blank=True, null=True)
    topic = models.ForeignKey(Topic, default=1, on_delete=models.CASCADE)
    num_true = models.IntegerField(blank=True, null=True, default=0)
    num_false = models.IntegerField(blank=True, null=True, default=0)
    rating = models.IntegerField(blank=True, null=True, default=0)
    num_show = models.IntegerField(blank=True, null=True, default=0)

    # voca = VocaManager()

    # class Meta:
    #     managed = False
    #     db_table = 'vocabulary'

    def __str__(self):
        return self.vocabulary_title


class Predict(models.Model):
    result = models.IntegerField(blank=True, null=True)
    vocabulary = models.ForeignKey(Vocabulary, on_delete=models.CASCADE)
    predict_txt = models.CharField(max_length=30, blank=True, null=True)
    id_user = models.ForeignKey(User, default=1, on_delete=True)
    time = models.DateTimeField(blank=True, null=True, default=timezone.now)


class Example(models.Model):
    vocabulary = models.ForeignKey(Vocabulary, on_delete=models.CASCADE)
    user = models.ForeignKey(User, default=1, on_delete=True)
    example_txt = models.CharField(max_length=45, blank=True, null=True)
    date_create = models.DateTimeField(blank=True, null=True, default=timezone.now)

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Vocabulary, Predict, Topic

STATUS_CHOICES = (
    (1, "NOUN"),
    (2, "VERB"),
    (3, "ADJECTIVE"),
    (4, "ADVERB"),
)


class VocabularyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(VocabularyForm, self).__init__(*args, **kwargs)
        self.fields['type'] = forms.ChoiceField(choices=STATUS_CHOICES)

    class Meta:
        model = Vocabulary
        fields = ['vocabulary_title', 'type', 'story', 'mean']


class PredictForm(forms.ModelForm):
    class Meta:
        model = Predict
        fields = ['vocabulary', 'predict_txt']


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['topic_title', 'topic_logo']


#
# class SongForm(forms.ModelForm):
#     class Meta:
#         model = Song
#         fields = ['song_title', 'audio_file']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
import random

from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from .forms import UserForm, TopicForm, VocabularyForm, PredictForm
from .models import Topic, Vocabulary, Example

# AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def create_topic(request):
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        form = TopicForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.user = request.user
            topic.topic_logo = request.FILES['topic_logo']
            file_type = topic.topic_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'topic': topic,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'music/create_topic.html', context)
            topic.save()
            return render(request, 'music/detail.html', {'topic': topic})
        context = {
            "form": form,
        }
        return render(request, 'music/create_topic.html', context)


def create_vocabulary(request, topic_id):
    form = VocabularyForm(request.POST or None, request.FILES or None)
    topic = get_object_or_404(Topic, pk=topic_id)
    print(form.data)
    if form.is_valid():
        topics_vocabularys = topic.vocabulary_set.all()
        for s in topics_vocabularys:
            if s.vocabulary_title == form.cleaned_data.get("vocabulary_title"):
                context = {
                    'topic': topic,
                    'form': form,
                    'error_message': 'You already added that vocabulary',
                }
                return render(request, 'music/create_vocabulary.html', context)
        vocabulary = form.save(commit=False)
        vocabulary.topic = topic
        vocabulary.save()
        return render(request, 'music/detail.html', {'topic': topic})
    context = {
        'topic': topic,
        'form': form,
    }
    return render(request, 'music/create_vocabulary.html', context)


def delete_topic(request, topic_id):
    topic = get_object_or_404(Topic, pk=topic_id)
    topic.delete()
    topics = Topic.objects.filter(user=request.user)
    return render(request, 'music/index.html', {'topics': topics})


def delete_vocabulary(request, topic_id, vocabulary_id, local_delete=1):
    topic = get_object_or_404(Topic, pk=topic_id)
    vocabulary = Vocabulary.objects.get(pk=vocabulary_id)
    vocabulary.delete()
    if int(local_delete) == 0:
        return render(request, 'music/detail.html', {'topic': topic})
    if int(local_delete) == 1:
        try:
            topics = Topic.objects.filter(user=request.user)
            vocabulary_ids = []
            for topic in topics:
                for vocabulary in topic.vocabulary_set.all():
                    vocabulary_ids.append(vocabulary.pk)
            users_vocabularys = Vocabulary.objects.filter(pk__in=vocabulary_ids)

        except Exception as e:
            users_vocabularys = []
        return render(request, 'music/vocabularys.html', {
            'vocabulary_list': users_vocabularys,
            'filter_by': 'all',
        })


def detail(request, topic_id):
    print('chay ham detal')
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        user = request.user
        topic = get_object_or_404(Topic, pk=topic_id)
        return render(request, 'music/detail.html', {'topic': topic, 'user': user})


def index(request):
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        topics = Topic.objects.filter(user=request.user)
        vocabulary_results = Vocabulary.objects.all()
        query = request.GET.get("q")
        if query:
            topics = topics.filter(
                Q(topic_title__icontains=query)
            ).distinct()
            vocabulary_results = vocabulary_results.filter(
                Q(vocabulary_title__icontains=query)
            ).distinct()
            return render(request, 'music/index.html', {
                'topics': topics,
                'vocabularys': vocabulary_results,
            })
        else:
            return render(request, 'music/index.html', {'topics': topics})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                topics = Topic.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'topics': topics})
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                topics = Topic.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'topics': topics})
    context = {
        "form": form,
    }
    return render(request, 'music/register.html', context)


def vocabularys(request, filter_by):
    # print(filter_by)
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        try:
            vocabulary_ids = []
            for topic in Topic.objects.filter(user=request.user):
                for vocabulary in topic.vocabulary_set.all():
                    vocabulary_ids.append(vocabulary.pk)
            users_vocabularys = Vocabulary.objects.filter(pk__in=vocabulary_ids)

        except Topic.DoesNotExist:
            users_vocabularys = []
        return render(request, 'music/vocabularys.html', {
            'vocabulary_list': users_vocabularys,
            'filter_by': filter_by,
        })


def compare_vocabualry(request, topic_id, type_compare):
    type_compare = int(type_compare)
    tempalte = ['music/etovn.html', 'music/VN2E.html', 'music/Story2E.html', 'music/Story2VN.html']
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    else:
        form = PredictForm(request.POST or None, request.FILES or None)
        topic = get_object_or_404(Topic, pk=topic_id)
        a = list(topic.vocabulary_set.all())
        ran = None
        if len(a) > 0:
            ran = random.choice(a)
        if request.method == 'POST':
            predict = form.save(commit=False)
            predict.user = request.user
            ran_old = form.cleaned_data['vocabulary']
            if type_compare == 0:
                compare = ran_old.mean
            else:
                compare = ran_old.vocabulary_title
            com = form.cleaned_data['predict_txt']
            if com is not None:
                com = com.lower()
            if com == compare.lower():
                ran_old.rating = (ran_old.num_false + 1) * 100.0 / (ran_old.num_show + 1)
                ran_old.num_true += 1
                ran_old.num_show += 1
                ran_old.save()
                predict.result = 1
                res = True
                message = 'Greate !!!'
            else:
                ran_old.rating = (ran_old.num_false + 1) * 100.0 / (ran_old.num_show + 1)
                ran_old.num_false += 1
                ran_old.num_show += 1
                ran_old.save()
                predict.result = 0
                res = False
                message = compare
            predict.vocabulary = ran_old
            predict.save()
            context = {
                "topic": topic,
                "form": form,
                "result": res,
                "error_message": message,
                "link": ran_old
            }
            print(context)
            return render(request, tempalte[type_compare], context)
        context = {
            "topic": topic,
            "new_word": ran,
            "form": form,
        }
        return render(request, tempalte[type_compare], context)


def update_voca():
    pass


def add_example():
    pass
def create_example(request, vocabulary_id,example):
    if not request.user.is_authenticated:
        return render(request, 'music/login.html')
    form = VocabularyForm(request.POST or None, request.FILES or None)
    vocabulary = get_object_or_404(Vocabulary, pk=vocabulary_id)
    if example is not None:
        new_exam=Example(example_txt=example,vocabulary=vocabulary,user=request.user)
        new_exam.save()
        return render(request, 'music/detail.html', {'vocabulary': vocabulary})
    context = {
        'vocabulary': vocabulary,
        'form': form,
    }
    return render(request, 'music/create_vocabulary.html', context)

music/templates/music/Story2E.html
{% extends 'music/base.html' %}
{% block title %}Add a New Word{% endblock %}
{% block topics_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="container-fluid">
        <div class="col-sm-12 col-md-12">
            <div class="panel panel-default">
                <div class="panel-body" style="text-align:center;" >
             <strong style="font-size: 2em;color:#002ba1;">{{topic.topic_title}}</strong>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-12 col-md-12">

            <ul class="nav nav-pills" style="margin-bottom: 15px;font-size: 2.5em;">
                <li role="presentation"><a href="{% url 'music:detail' topic.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'music:create_vocabulary' topic.id %}">Add New Word</a></li>
                <li role="presentation" ><a href="{% url 'music:compare_word' topic.id 0%}">EngLish to VN</a></li>
                <li role="presentation" ><a href="{% url 'music:compare_word' topic.id 1%}">VN to English</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:compare_word' topic.id 2%}">Story to English</a></li>
            </ul>

            <!--TEST POP UP-->
            <div id="modal-wrapper" class="modal">
                <form class="modal-content animate">
                    <div class="imgcontainer">
                    <span onclick="document.getElementById('modal-wrapper').style.display='none'" class="close" title="Close
                          PopUp">&times;</span>
                        <img src="https://img.vietwiki.net/uploads/2018/01/trieu-le-dinh-1.jpg" alt="Avatar" class="avatar">
                        <br>
                        <strong style="text-align:center;font-size: 2.5em;color:#1c011a;">{{link.vocabulary_title}}</strong>
                        <br>
                    </div>
                    <div class="w3-container" style="text-align:center">
                        <h2 style="font-size: 2em;"><font color="#1c911a">{{link.mean}}</font></h2>
                        <span><font size="7" color="#4542f5">{{link.story}}</font></span>
                        <br>
                        {% for example in link.example_set.all %}
                        <span><font size="6" color="#ed6707">{{ example.example_txt }}</font></span>
                        <br>
                        {% endfor %}
                        <form action="/action_page.php">
                            <input class="predict_txt" name="Example" placeholder="New example" style="width:85%;margin-top: 10%;font-size:1em;">
                            <br>
                            <button type="submit" class="button_1" style="width:85%;margin-top: 5%;font-size:1em;">Add new</button>

                        </form>

                    </div>

                </form>

            </div>

            <!--VIEW-->
            <div>
                <div style="text-align:center">
                    {% if new_word %}
                    <strong style="font-size: 5em;">{{new_word.story}}</strong>
                    <form class="form-horizontal" role="form" action="" method="POST" enctype="multipart/form-data"
                    style="margin-top:5%;" autocomplete="off">
                        {% csrf_token %}
                        <input class="input_predict" name="predict_txt" style="font-size: 5em;">
                        <input type="hidden" name="vocabulary" value="{{new_word.id}}">
                        <button id="submitword" type="submit" class="button_1" style="font-size: 4em;margin-top:3%;">Submit</button>
                    </form>
                    {% endif %}
                    {% if error_message %}
                    <div style="margin: auto;">
                    <strong role="presentation" style="font-size: 4em; color:#1a75ff">{{link.story}}</strong>
                    </div>
                    {% if result %}
                    <div class="alert" style="background-color:#00994d;font-size: 2em;">
                        <strong style="font-size: 2em;">{{error_message}}!</strong>
                        <br>
                        <button class="button_1"
                                onclick="document.getElementById('modal-wrapper').style.display='block'"
                        style="width:40%;margin-top:15%;font-size: 1.3em;background-color: #eb7609;">
                            Revise
                        </button>
                        <button class="button_1"
                                onclick="window.location.href='{% url 'music:compare_word' topic.id 2%}'"
                        style="width:40%;margin-top:15%;font-size: 1.3em;background-color: #eb7609;">
                            Continues
                        </button>
                    </div>
                    {% else %}
                    <div class="alert" style="background-color:#e00b0b;font-size: 2em;">
                        <strong style="font-size: 2em;">{{error_message}}</strong>
                        <br>
                        <br>
                        <strong>What a pity !!!</strong>
                        <br>
                        <button class="button_1"
                                onclick="document.getElementById('modal-wrapper').style.display='block'"
                        style="width:40%;margin-top:15%;font-size: 1.3em;background-color: #eb7609;">
                            Revise
                        </button>
                        <button class="button_1"
                                onclick="window.location.href='{% url 'music:compare_word' topic.id 2%}'"
                        style="width:40%;margin-top:15%;font-size: 1.3em;background-color: #eb7609;">
                            Continues
                        </button>
                    </div>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/Story2VN.html
{% extends 'music/base.html' %}
{% block title %}Add a New Word{% endblock %}
{% block topics_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
<!--                    <a href="{% url 'music:detail' topic.id %}">-->
<!--                        {% if topic.topic_logo %}-->
<!--                        <img src="{{ topic.topic_logo.url }}" class="img-responsive">-->
<!--                        {% else %}-->
<!--                        <h3>No image to display</h3>-->
<!--                        {% endif %}-->
<!--                    </a>-->

                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 15px;font-size: 2.5em;">
                <li role="presentation"><a href="{% url 'music:detail' topic.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'music:create_vocabulary' topic.id %}">Add New Word</a></li>
                <li role="presentation" ><a href="{% url 'music:compare_word' topic.id 0%}">EngLish to
                    VN</a></li>
                <li role="presentation" ><a href="{% url 'music:compare_word' topic.id 1%}">VN to English</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:compare_word' topic.id 3%}">Story to English</a></li>
            </ul>
            <!--TEST POP UP-->
            <div id="modal-wrapper" class="modal">
                <form class="modal-content animate">
                    <div class="imgcontainer">
                    <span onclick="document.getElementById('modal-wrapper').style.display='none'" class="close" title="Close
                          PopUp">&times;</span>
                        <img src="{{link.note}}" alt="Avatar" class="avatar">
                        <h1 style="text-align:center">{{link.vocabulary_title}}</h1>
                    </div>
                    <div class="w3-container" style="text-align:center">
                        <h2><font size="10" color="#1c911a">{{link.mean}}</font></h2>
                        <span><font size="5" color="#4542f5">{{link.story}}</font></span><br>
                        example:<br>
                        {% for example in link.example_set.all %}
                        <span><font size="4" color="#ed6707">{{ example.example_txt }}</font></span>
                        <br>
                        {% endfor %}
                        <form action="/action_page.php">
                            <input type="text" name="Example" placeholder="New example">
                            <br>
                            <button type="submit" class="button_1">ADD new</button>

                        </form>

                    </div>

                </form>

            </div>

            <!--VIEW-->
            <div >
                <div style="text-align:center">
                    {% if new_word %}
                    <span style="text-align:center"><font size="9">{{new_word.story}}</font></span>
                    <form class="form-horizontal" role="form" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input class="input_predict" name="predict_txt">
                        <input type="hidden" name="vocabulary" value="{{new_word.id}}">
                        <button id="submitword" type="submit" class="button_1">Submit</button>
                    </form>
                    {% endif %}
                    {% if error_message %}
                    <div style="margin: auto;">
                    <span role="presentation"><font size="8" color="#1a75ff">{{link.vocabulary_title}}</font></span>
                    </div>
                    {% if result %}
                    <div class="alert" style="background-color:#00994d;">
                        <strong>{{error_message}}!</strong>
                        <br>
                        <button class="button_2"
                                onclick="document.getElementById('modal-wrapper').style.display='block'">
                            Revise
                        </button>
                        <button class="button_2"
                                onclick="window.location.href='{% url 'music:compare_word' topic.id 3%}'">
                            Continues
                        </button>
                    </div>
                    <script>
                 document.getElementById("submitword").disabled = true;

                    </script>
                    {% else %}
                    <div class="alert">
                        <strong style=""><font size="8">{{error_message}}</font></strong> what a pity !!!
                        <br>
                        <button class="button_2"
                                onclick="document.getElementById('modal-wrapper').style.display='block'">
                            Revise
                        </button>
                        <button class="button_2"
                                onclick="window.location.href='{% url 'music:compare_word' topic.id 3%}'">
                            Continues
                        </button>
                    </div>
                    <script>
                  document.getElementById("submitword").disabled = true;

                    </script>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/Top.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>hguygwe weugduwed weudhgwiued </h2>
</body>
</html>

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}RemWord{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'music/popup.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
    <script src="{% static 'music/js/popup.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">RemWord</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="{% block topics_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>&nbsp; Topics</a></li>
                <li class="{% block vocabularys_active %}{% endblock %}"><a href="{% url 'music:vocabularys' 'all' %}"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span>&nbsp; Vocabularys</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                    <button type="submit" class="btn btn-default">Search</button>
                </div>

            </form>
            <ul class="nav navbar-nav navbar-right">
                 <li>
                    <a href="{% url 'music:create_topic' %}">
                        <span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span>&nbsp; Practice
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:create_topic' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Word
                    </a>
                </li>

                <li>
                    <a href="{% url 'music:create_topic' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Topic
                    </a>

                </li>

                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>

            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}RemWord{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">RemWord</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>